server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: stridehr-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: stridehr-api
          __path__: /app/logs/*.log

  - job_name: stridehr-frontend
    static_configs:
      - targets:
          - localhost
        labels:
          job: stridehr-frontend
          __path__: /var/log/nginx/*.log

  - job_name: mysql
    static_configs:
      - targets:
          - localhost
        labels:
          job: mysql
          __path__: /var/log/mysql/*.log

  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: system
          __path__: /var/log/syslog

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log

# Pipeline stages for log processing
  - job_name: stridehr-structured-logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: stridehr-structured
          __path__: /app/logs/structured-*.json
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            source: source
      - timestamp:
          source: timestamp
          format: RFC3339
      - labels:
          level:
          source: