global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'stridehr-api'
    static_configs:
      - targets: ['stridehr-api-prod:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'mysql'
    static_configs:
      - targets: ['stridehr-mysql-prod:3306']
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['stridehr-redis-prod:6379']
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['stridehr-nginx-prod:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s